// Builds simulated XML responses for both protocols.
//
// OK responses mimic the usual Epson ePOS-Print response structure
// (<response success="..." code="..." status="..."/>) and Fiscal RT services
// (<response> with extra fiscalReceiptNumber/zRepNumber fields). They have no
// real fiscal value; they only return a plausible response so POS software can
// continue its development/debug flow.

const EPOS_ERROR_CODES = {
  'offline': { code: 'EPTR_OFFLINE', status: 8 },
  'paper-end': { code: 'EPTR_REC_EMPTY', status: 8 },
  'cover-open': { code: 'EPTR_COVER_OPEN', status: 4 },
  'generic-error': { code: 'EPTR_UNRECOVERABLE', status: 1 },
  'fiscal-error': { code: 'EPTR_UNRECOVERABLE', status: 1 },
};

const FISCAL_ERROR_CODES = {
  'offline': 'PRINTER_OFFLINE',
  'paper-end': 'PAPER_END',
  'cover-open': 'COVER_OPEN',
  'generic-error': 'GENERIC_ERROR',
  'fiscal-error': 'FISCAL_ERROR',
};

function xmlEscape(s) {
  return String(s ?? '').replace(/[<>&'"]/g, (c) => ({
    '<': '&lt;',
    '>': '&gt;',
    '&': '&amp;',
    "'": '&apos;',
    '"': '&quot;',
  }[c]));
}

function buildEposOkResponse() {
  return `<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
 <soapenv:Body>
  <response xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print" success="true" code="" status="0" battery="100"/>
 </soapenv:Body>
</soapenv:Envelope>
`;
}

function buildEposErrorResponse(printerStatus) {
  const info = EPOS_ERROR_CODES[printerStatus] || EPOS_ERROR_CODES['generic-error'];
  return `<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
 <soapenv:Body>
  <response xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print" success="false" code="${info.code}" status="${info.status}" battery="100"/>
 </soapenv:Body>
</soapenv:Envelope>
`;
}

function buildFiscalOkResponse(meta = {}) {
  const fields = [
    ['printerStatus', 'online'],
    ['fiscalReceiptNumber', meta.fiscalReceiptNumber],
    ['fiscalReceiptDate', meta.fiscalReceiptDate],
    ['fiscalReceiptTime', meta.fiscalReceiptTime],
    ['zRepNumber', meta.zRepNumber],
    ['fiscalReceiptAmount', meta.total],
  ].filter(([, v]) => v !== undefined && v !== null);

  const inner = fields.map(([k, v]) => `  <${k}>${xmlEscape(v)}</${k}>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<response success="true" code="" status="0">
${inner}
</response>
`;
}

function buildFiscalErrorResponse(printerStatus) {
  const code = FISCAL_ERROR_CODES[printerStatus] || 'GENERIC_ERROR';
  const extra = printerStatus === 'fiscal-error'
    ? '\n  <fiscalError code="EF999" description="Simulated fiscal error (sim-epos)"/>'
    : '';
  return `<?xml version="1.0" encoding="UTF-8"?>
<response success="false" code="${code}" status="1">
  <printerStatus>${printerStatus}</printerStatus>${extra}
</response>
`;
}

// Deliberately invalid response, useful for testing client robustness.
function buildInvalidXmlResponse(protocol) {
  if (protocol === 'fiscal') {
    return '<?xml version="1.0" encoding="UTF-8"?>\n<response success="true" code"" status=0\n<!-- Truncated/invalid XML deliberately generated by sim-epos -->';
  }
  return '<?xml version="1.0" encoding="utf-8"?>\n<soapenv:Envelope><soapenv:Body><response success="true" code="" status="0"\n<!-- Truncated/invalid XML deliberately generated by sim-epos -->';
}

module.exports = {
  buildEposOkResponse,
  buildEposErrorResponse,
  buildFiscalOkResponse,
  buildFiscalErrorResponse,
  buildInvalidXmlResponse,
};
